packages_sources = function() {
  #Created by Daniel Ca?ueto 07/09/2016
  #Loading of libraries and functions

  # suppressPackageStartupMessages(requireNamespace("minpack.lm", quietly = TRUE)
  # suppressPackageStartupMessages(requireNamespace("reshape", quietly = TRUE)
  # suppressPackageStartupMessages(requireNamespace("ggplot2", quietly = TRUE)
  # suppressPackageStartupMessages(requireNamespace("compiler", quietly = TRUE)
  # suppressPackageStartupMessages(requireNamespace("robust", quietly = TRUE)
  # suppressPackageStartupMessages(requireNamespace("apcluster", quietly = TRUE)
  # suppressPackageStartupMessages(requireNamespace("rio", quietly = TRUE)
   if (!suppressPackageStartupMessages(require("minpack.lm"))) install.packages("minpack.lm")
   if (!suppressPackageStartupMessages(require("reshape"))) install.packages("reshape")
   if (!suppressPackageStartupMessages(require("compiler"))) install.packages("compiler")
   if (!suppressPackageStartupMessages(require("robust"))) install.packages("robust")
   if (!suppressPackageStartupMessages(require("rio"))) install.packages("rio")
   if (!suppressPackageStartupMessages(require("png"))) install.packages("png")
   if (!suppressPackageStartupMessages(require("plotly"))) install.packages("plotly")
  if (!suppressPackageStartupMessages(require("DT"))) install.packages("DT")
  if (!suppressPackageStartupMessages(require("D3TableFilter"))) install.packages("D3TableFilter")
  if (!suppressPackageStartupMessages(require("shiny"))) install.packages("shiny")
  if (!suppressPackageStartupMessages(require("fields"))) install.packages("fields")
  if (!suppressPackageStartupMessages(require("apcluster"))) install.packages("apcluster")
  if (!suppressPackageStartupMessages(require("heatmaply"))) install.packages("heatmaply")
  if (!suppressPackageStartupMessages(require("missForest"))) install.packages("missForest")
  if (!suppressPackageStartupMessages(require("stringr"))) install.packages("stringr")
  if (!suppressPackageStartupMessages(require("mQTL.NMR"))) install.packages("mQTL.NMR")
  
  source("recurAlign.R")
source("alignSp.R")
source("localrecurAlign.R")
source("FFTcorr.R")
source("shift.R")
source("corrcoef_aligned.R")
source("findMid.R")
  source('fhs.R')
  source('clustspectraplot.R')
  source('alignment.R')
  source('peak_analysis.R')
  
  source('sign_par.R')
  source('signals_int.R')
  source("interface_quant.R")
  source("save_roi_testing.R")
  source("remove_quant.R")
  source("fittingloop.R")
  source("fittingloop_bg.R")
  source("outputgenerator.R")
  source("plotgenerator.R")
  source("interface_quant.R")
  source("fitting_optimization.R")
  source("peakpvoigt.R")
  source('autorun_model_spectrum.R')
  source("peakdet.R")
  source("fitting_prep.R")
  source("integration.R")
  source("autorun.R")
  source("Metadata2Buckets.R")
  source("readspectrum.R")
  source("jtp.R")
  source("import_data.R")
  source("save_output.R")
  source("fitting_variables.R")
  source("automatic_roi_edition.R")
  source("validation.R")
  source("plele.R")
  source("interface_integration.R")
  source("p_values.R")
  
  

}
