packages_sources = function() {
  #Created by Daniel Ca?ueto 07/09/2016
  #Loading of libraries and functions

  # requireNamespace("minpack.lm", quietly = TRUE)
  # requireNamespace("reshape", quietly = TRUE)
  # requireNamespace("ggplot2", quietly = TRUE)
  # requireNamespace("compiler", quietly = TRUE)
  # requireNamespace("robust", quietly = TRUE)
  # requireNamespace("apcluster", quietly = TRUE)
  # requireNamespace("rio", quietly = TRUE)
   if (!require("minpack.lm")) install.packages("minpack.lm")
   if (!require("reshape")) install.packages("reshape")
   if (!require("compiler")) install.packages("compiler")
   if (!require("robust")) install.packages("robust")
   if (!require("rio")) install.packages("rio")
   if (!require("png")) install.packages("png")
   if (!require("plotly")) install.packages("plotly")
  if (!require("DT")) install.packages("DT")
  if (!require("D3TableFilter")) install.packages("D3TableFilter")
  if (!require("shiny")) install.packages("shiny")
  if (!require("fields")) install.packages("fields")
  if (!require("apcluster")) install.packages("apcluster")
  if (!require("heatmaply")) install.packages("heatmaply")
  if (!require("missForest")) install.packages("missForest")
  if (!require("stringr")) install.packages("stringr")
  
  
  source('fhs.R')
  source('clustspectraplot.R')
  
  source('sign_par.R')
  source('signals_int.R')
  source("interface_quant.R")
  source("save_roi_testing.R")
  source("remove_quant.R")
  source("fittingloop.R")
  source("fittingloop_bg.R")
  source("outputgenerator.R")
  source("plotgenerator.R")
  source("interface_quant.R")
  source("fitting_optimization.R")
  source("peakpvoigt.R")
  source('autorun_model_spectrum.R')
  source("peakdet.R")
  source("fitting_prep.R")
  source("integration.R")
  source("autorun.R")
  source("Metadata2Buckets.R")
  source("readspectrum.R")
  source("jtp.R")
  source("import_data.R")
  source("save_output.R")
  source("fitting_variables.R")
  source("automatic_roi_edition.R")
  source("validation.R")
  source("plele.R")
  source("interface_integration.R")
  
  

}
