packages_sources = function() {
  #Created by Daniel Ca?ueto 07/09/2016
  #Loading of libraries and functions

  # suppressPackageStartupMessages(requireNamespace("minpack.lm", quietly = TRUE)
  # suppressPackageStartupMessages(requireNamespace("reshape", quietly = TRUE)
  # suppressPackageStartupMessages(requireNamespace("ggplot2", quietly = TRUE)
  # suppressPackageStartupMessages(requireNamespace("compiler", quietly = TRUE)
  # suppressPackageStartupMessages(requireNamespace("robust", quietly = TRUE)
  # suppressPackageStartupMessages(requireNamespace("apcluster", quietly = TRUE)
  # suppressPackageStartupMessages(requireNamespace("rio", quietly = TRUE)
   if (!suppressPackageStartupMessages(require("minpack.lm"))) install.packages("minpack.lm")
   if (!suppressPackageStartupMessages(require("reshape"))) install.packages("reshape")
   if (!suppressPackageStartupMessages(require("compiler"))) install.packages("compiler")
   if (!suppressPackageStartupMessages(require("robust"))) install.packages("robust")
   if (!suppressPackageStartupMessages(require("rio"))) install.packages("rio")
   if (!suppressPackageStartupMessages(require("png"))) install.packages("png")
   if (!suppressPackageStartupMessages(require("plotly"))) install.packages("plotly")
  if (!suppressPackageStartupMessages(require("DT"))) install.packages("DT")
  if (!suppressPackageStartupMessages(require("shiny"))) install.packages("shiny")
  if (!suppressPackageStartupMessages(require("fields"))) install.packages("fields")
  if (!suppressPackageStartupMessages(require("apcluster"))) install.packages("apcluster")
  if (!suppressPackageStartupMessages(require("heatmaply"))) install.packages("heatmaply")
  if (!suppressPackageStartupMessages(require("missForest"))) install.packages("missForest")
  if (!suppressPackageStartupMessages(require("speaq"))) install.packages("speaq")
  
  if (!suppressPackageStartupMessages(require("stringr"))) install.packages("stringr")
    if (!suppressPackageStartupMessages(require("mQTL.NMR"))) {
      source("https://bioconductor.org/biocLite.R")
      biocLite("mQTL.NMR")
    }
    if (!suppressPackageStartupMessages(require("D3TableFilter"))) {
      if (!suppressPackageStartupMessages(require("devtools"))) install.packages("devtools")        
      devtools::install_github("rstudio/crosstalk")
      devtools::install_github("ThomasSiegmund/D3TableFilter")
    }
  
  source("recurAlign.R")
source("alignSp.R")
source("localRecurAlign.R")
source("FFTcorr.R")
source("shift.R")
source("corrcoef_aligned.R")
source("findMid.R")
  source("matchSegments.R")
  source("comparePeaks.R")
  source("zeroPad.R")
  source("getCorellation.R")
  
  
  source('fhs.R')
  source('clustspectraplot.R')
  source('alignment.R')
  source('peak_analysis.R')
  
  source('sign_par.R')
  source('signals_int.R')
  source("interface_quant.R")
  source("save_roi_testing.R")
  source("remove_quant.R")
  source("fittingloop.R")
  source("fittingloop_bg.R")
  source("output_generator.R")
  source("plotgenerator.R")
  source("interface_quant.R")
  source("fitting_optimization.R")
  source("peakpvoigt.R")
  source('autorun_model_spectrum.R')
  source("peakdet.R")
  source("fitting_prep.R")
  source("integration.R")
  source("autorun.R")
  source("Metadata2Buckets.R")
  source("readspectrum.R")
  source("jtp.R")
  source("import_data.R")
  source("save_output.R")
  source("fitting_variables.R")
  source("automatic_roi_edition.R")
  source("validation.R")
  source("plele.R")
  source("interface_integration.R")
  source("p_values.R")
  source("write_info.R")
  
  
  recurAlign=cmpfun(recurAlign)
  alignSp=cmpfun(alignSp)
  localRecurAlign=cmpfun(localRecurAlign)
  FFTcorr=cmpfun(FFTcorr)
  shift=cmpfun(shift)
  corrcoef_aligned=cmpfun(corrcoef_aligned)
  findMid=cmpfun(findMid)
  matchSegments=cmpfun(matchSegments)
  comparePeaks=cmpfun(comparePeaks)
  zeroPad=cmpfun(zeroPad)
  getCorellation=cmpfun(getCorellation)
  write_info=cmpfun(write_info)
  
  fhs=cmpfun(fhs)
  clustspectraplot=cmpfun(clustspectraplot)
  alignment=cmpfun(alignment)
  peak_analysis=cmpfun(peak_analysis)
  
  sign_par=cmpfun(sign_par)
  signals_int=cmpfun(signals_int)
  interface_quant=cmpfun(interface_quant)
  save_roi_testing=cmpfun(save_roi_testing)
  remove_quant=cmpfun(remove_quant)
  fittingloop=cmpfun(fittingloop)
  fittingloop_bg=cmpfun(fittingloop_bg)
  output_generator=cmpfun(output_generator)
  plotgenerator=cmpfun(plotgenerator)
  interface_quant=cmpfun(interface_quant)
  fitting_optimization=cmpfun(fitting_optimization)
  peakpvoigt=cmpfun(peakpvoigt)
  autorun_model_spectrum=cmpfun(autorun_model_spectrum)
  peakdet=cmpfun(peakdet)
  fitting_prep=cmpfun(fitting_prep)
  integration=cmpfun(integration)
  autorun=cmpfun(autorun)
  Metadata2Buckets=cmpfun(Metadata2Buckets)
  # readspectrum=cmpfun(readspectrum)
  # jtp=cmpfun(jtp)
  import_data=cmpfun(import_data)
  save_output=cmpfun(save_output)
  fitting_variables=cmpfun(fitting_variables)
  automatic_roi_edition=cmpfun(automatic_roi_edition)
  validation=cmpfun(validation)
  plele=cmpfun(plele)
  interface_integration=cmpfun(interface_integration)
  p_values=cmpfun(p_values)
  topspin_read_spectrum2=cmpfun(topspin_read_spectrum2)
  parseAcqus=cmpfun(parseAcqus)
  parseProcs=cmpfun(parseProcs)
}
